### ISSUE TITLE
Improve SDK archive page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1656]
This is an umbrella issue for requests for https://dart.dev/tools/sdk/archive:

* [x] dart-lang/site-shared#96: UI freezes
* [x] dart-lang/site-shared#97: SDK Archive sorting is weird
* [ ] #89: Download archive should use analytics
* [x] #75: Use `sdk_builds` package for archive page

/cc @johnpryan @domesticmouse

**Comment by kwalrath** [comment]
I added a couple of other bugs (very old) to the list.

**Comment by johnpryan** [comment]
Quick update: it looks like we will be able to use the `sdk_builds` package (#75) but either way there needs to be a fair number of network calls in order to display the correct version for pre-1.11.0-dev.0.0 since those are SVN revisions.

I'm going to start with a PR that updates to using sdk_builds (#75) and uses the `sdk_builds`package  (dart-lang/site-shared#97) and leave analytics and performance issues for the next iteration

**Comment by johnpryan** [comment]
FWIW we do have the option of greatly improving the performance  if we manually mapped the SVN revisions to version strings:

using the `getVersionPaths()` from `package:sdk_builds` is a single HTTP call but results in SVN versions mixed with the others:

<img width="176" alt="Screen Shot 2019-06-04 at 4 52 50 PM" src="https://user-images.githubusercontent.com/1145719/58920943-4e429880-86e9-11e9-90e0-7e38fdf9539b.png">

then we could lazy-load the full VersionInfo object when the user selects the dropdown.

`package:sdk_builds` could just provide a hard-coded Map from the SVN revision to the Dart version since that information won't change

**Comment by johnpryan** [comment]
I have a working prototype [here](https://github.com/johnpryan/dart_sdk_archive) that uses a dart 2 compatible branch of `sdk_builds` (kevmoo/sdk_builds.dart#1).

I'm currently running into an issue with the googleapis Storage class provided by `sdk_builds` and filed an issue here (dart-lang/googleapis#73)

**Comment by kwalrath** [comment]
Is the prototype staged anywhere?

**Comment by johnpryan** [comment]
http://jpryan.me/dart_sdk_archive/

**Comment by johnpryan** [comment]
Since the only remaining issue is https://github.com/dart-lang/site-www/issues/89, I'm going to close this so we can just track that specific issue.
