### ISSUE TITLE
2019Q4 work log

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#2041]
_Reorder items using drag-and-drop_.

**Active**ly being worked on:
- [ ] Test all code excerpts #1803
  - [ ] Homepage Try-Dart example code issues #2126
  - [x] Asynchronous programming codelab: consider updates to example code #2128
    - In particular, note the agreement that: "pretty much **all example code** should be **free of analyzer issues** when configured with the **pedantic** options".
- [ ] ...

**Next: top**

- [ ] Run web tests using headless chrome. Related: #450, #529. We might be doing this already.
- [ ] CI: check external links via cron build #1247
- [ ] Re. https://github.com/dart-lang/site-www/pull/2065#issuecomment-551232413: consider using the default file name `analyzer-results.txt` instead of `analyzer-results-stable.txt` for stable-based builds.

**Other**:

- [ ] Link anchors are missing #2061
- [ ] main.scss: bootstrap_config_shared import in wrong order #2007
- [ ] Background color for neutral code snippets is too similar to bad one #1093

**Block/awaiting**:
- [ ] Upgrade to Jekyll 4 and the latest jekyll-assets #2043
- [ ] ...

**Submitted**:
- [ ] ...

**Done, deployed and confirmed** (selected):
- [x] Support loading DartPad sources from site vs Gist #1919
- [x] Books page issues: ToC links don't work, and covers have external link icons #2060
- [x] Upgrade node to v12 #2042
- [x] Update firebase-tools 7.3.2 → 7.6.1 #2053
- [x] Upgrade ruby and gems #2040
- [x] Gemfile references deprecated Sass library #1758

**Related**:

- Dart 2.6.0-dev analyzer: issues format differs from stable 2.5 release format https://github.com/dart-lang/sdk/issues/38957

**Comment by parlough** [comment]
I'm going to close this as all remaining tasks seem to have an associated issue and this was for 2019. Thanks for all the great work, it makes working on the site a pleasure.

**Comment by chalin** [comment]
My time flies! Thanks for the kind words @parlough.
