### ISSUE TITLE
Change URLs for command-line tools being replaced by `dart`

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2719]
We'll follow a variant of the pub precedent but NOT update any pub URLs: (/tools/pub/cmd/pub-outdated, e.g.). Here are the new URLs we'll use:

* [x] /tools/dart-analyze (redirect from /tools/dartanalyzer)
* [x] /tools/dart-compile (redirect from /tools/dart2native and, eventually from /tools/dart2js)
* [x] /tools/dart-create 
* [x] /tools/dart-format (redirect from /tools/dartfmt) (#2982)
* [x] /tools/dart-pub (created for URL guessers; redirect **to** /tools/pub/cmd) (#3367)
* [x] /tools/dart-run (redirect from /tools/dart-vm and probably /tools/pub/cmd/pub-run) (#3154)
* [x] /tools/dart-test (replaces `pub run test`) (#3369)

Other notes:
* Should probably redirect from /tools/dart-vm to /tools/dart-run.
* We'll need to do a search for the old command names _and_ for `dart-tool`, so we can update links. 
* We'll keep the old command name on the page, for searchability and to help users who find/know about the old name.
* No change (for now, at least) to the following pages under /tools/:
    * build_runner
    * dart-devtools
    * dartaotruntime (deliberately a standalone file; the smallest VM we have for running code, usable only on the output of `dart compile aot-snapshot`)
    * dartdevc (not sure whether this will stay a separate command; /cc @kevmoo)
    * dartdoc (verb still to be added)
    * dartpad
    * webdev

**Comment by kwalrath** [comment]
I'm starting work on the dart-test page and dart-pub redirect.
