### ISSUE TITLE
TODO(chalin): use $site-color-codeblock-bg 

### ISSUE THREAD

**Issue by woinbo** [dart-lang/site-www#2852]
### we need to refactor these TODO's if someone interested does comment on this issue.

Find pages with TODO's, and refactor them by changing code or add new code to that file.

Here's a list of the 11 pages we should look at and eventually update (there might be more that don't show up due to improper formatting):
* Style Related
- [ ] TODO(chalin): use $site-color-codeblock-bg? [link to file](https://github.com/dart-lang/site-www/blob/63393923a1854289bb37e4919a37ec294d2ae887/src/_assets/css/_code.scss)
- [ ] TODO(chalin): 1.5rem; [link to file](https://github.com/dart-lang/site-www/blob/63393923a1854289bb37e4919a37ec294d2ae887/src/_assets/css/_code.scss)
  
- [ ]  TODO: drop once heading class styles (like .h4) are fixed. [link to file](https://github.com/dart-lang/site-www/blob/dd7abec8d8b31c4d8a78c7c469d3186c99d74512/src/_assets/css/_books.scss)
- [ ]  TODO: use / override BS defaults named $hX-font-size. [link to file](https://github.com/dart-lang/site-www/blob/72296bcbb1654e9c13f21f06b71b97af9ff0a67b/src/_assets/css/_variables.scss)
 
* Dart analyze
 - [ ]  TODO @johnpryan: After dart CLI ships in stable, use dart analyze for all channels. [link to file](https://github.com/dart-lang/site-www/blob/dd7abec8d8b31c4d8a78c7c469d3186c99d74512/tool/dart_tools/bin/update_analyzer_txt.dart)
 
- [ ]  TODO(chalin): as of 2019/11/17, we don't need to select individual browser test files. Run browser tests over all files, since VM-only tests have been annotated as such.
   [link to file](https://github.com/dart-lang/site-www/blob/76d9015dd35c93dde25cbbeb2c2a0594e32ebd85/tool/analyze-and-test-examples.sh)
 * Regexp
 - [ ]  TODO: maybe style special characters inside a regexp as punctuation. [link to file](https://github.com/dart-lang/site-www/blob/dd7abec8d8b31c4d8a78c7c469d3186c99d74512/src/_assets/js/vendor/code-prettify/prettify.js)

* Version related:
 - [ ] TODO: identify versions (on line number 767)
 - [ ] TODO: identify versions (on line number 781) [link to file](https://github.com/dart-lang/site-www/blob/dd7abec8d8b31c4d8a78c7c469d3186c99d74512/src/_assets/js/vendor/jquery-3.4.1.js)

- [ ]  TODO: Next time we update this page, remove the `toc` line above. [link to file](https://github.com/dart-lang/site-www/blob/dd7abec8d8b31c4d8a78c7c469d3186c99d74512/src/_guides/whats-new.md)
* Fix build instructions
 - [ ]  TODO (https://github.com/dart-lang/site-www/issues/2219): Fix build instructions.[link to file](https://github.com/dart-lang/site-www/blob/cf25ea5799641d55e2cd9aeb24a9a04c54c242e8/src/_guides/libraries/c-interop.md)

- [ ] TODO: Give an example of how to deploy with Firebase, which originally was shown on [link to file](https://github.com/dart-lang/site-www/blob/72296bcbb1654e9c13f21f06b71b97af9ff0a67b/src/web/deployment.md)
- [ ]  TODO: Improve the formatting of the following diff [link to file](https://github.com/dart-lang/site-www/blob/09c64cce74aefc625d768136c1669d98efb665c1/src/tools/pub/cmd/pub-outdated.md)

- [ ]  TODO: (https://github.com/dart-lang/site-www/issues/2171) [link to file](https://github.com/dart-lang/site-www/blob/0b3ff7f8ea6e2117ac9fcffe018d709f150a039f/src/_guides/language/extension-methods.md)

- [ ] TODO: update that screenshot [link to file](https://github.com/dart-lang/site-www/blob/5296a63c65d3d9e11ab77d62e759ab97b9d76e66/src/null-safety/index.md)

@kwalrath will assign the task's

**Comment by kwalrath** [comment]
Actually... What I meant was to file one issue per group of TODOs. So one issue for the style TODOs, one for the dart analyze TODOs, etc. Then create one or more PRs to point from each TODO to the relevant issue.

**Comment by woinbo** [comment]
Sorry, @kwalrath I took it wrong but I have fixed the mistake with these relevant issues #2859 #2860 #2861 #2862 #2863. I have one question what about the issues which don't lay in any category. Should I create one single issue for those?

**Comment by kwalrath** [comment]
> Sorry, @kwalrath I took it wrong but I have fixed the mistake with these relevant issues #2859 #2860 #2861 #2862 #2863.

Thank you!

> I have one question what about the issues which don't lay in any category. Should I create one single issue for those?

One issue per category-less TODO, please. Thanks again!
