### ISSUE TITLE
Address TODOs in build instructions

### ISSUE THREAD

**Issue by woinbo** [dart-lang/site-www#2863]
We have the following TODOs related to build instructions:

 - [ ]  TODO (https://github.com/dart-lang/site-www/issues/2219): Fix build instructions.[link to file](https://github.com/dart-lang/site-www/blob/master/src/_guides/libraries/c-interop.md)
- [ ] TODO: Give an example of how to deploy with Firebase, which originally was shown on [link to file](https://github.com/dart-lang/site-www/blob/master/src/web/deployment.md)
- [ ]  TODO: Improve the formatting of the following diff [link to file](https://github.com/dart-lang/site-www/blob/master/src/tools/pub/cmd/pub-outdated.md)
- [ ]  TODO: (https://github.com/dart-lang/site-www/issues/2171) [link to file](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/extension-methods.md)
- [ ] TODO: update that screenshot [link to file](https://github.com/dart-lang/site-www/blob/master/src/null-safety/index.md)

cc: @kwalrath #2119

**Comment by kwalrath** [comment]
We should clarify these TODOs.

**Comment by parlough** [comment]
Thanks for tracking these! It looks like most are fixed or tracked in other issues now. I created https://github.com/dart-lang/site-www/issues/5029 to track the Firebase one.
