### ISSUE TITLE
Address TODOs in the language tour

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2950]
I'm about to create a PR for the first phase of migrating the language tour to null safety. Like the Effective Dart migration (#2944), I'm starting with just the code and the text directly affected by the code. Subsequent PRs will add info about null safety features and address known issues.

This issue is intended to track progress on all the TODOs in the language tour that aren't already covered by another issue.

**Comment by kwalrath** [comment]
Also, make sure that the second item under "Important concepts" says something about`Object?` working "if you opt into null safety", with a link to where those instructions are.

**Comment by kwalrath** [comment]
The urgent TODOs have been addressed, I think.

**Comment by vendz** [comment]
**Updating to a format similar to (#2683)**

we have the following todos related to the language tour:

- [x] Also, make sure that the second item under "Important concepts" says something aboutObject? working "if you opt into null safety", with a link to where those instructions are.
- [ ] TODO(miquelbeltran) language-tour.md should explain that non-required params can be null

**Comment by kwalrath** [comment]
Just confirmed that these TODOs are no longer in the source code and have presumably been addressed.

**Comment by kwalrath** [comment]
Reopened because there are still some TODOs in language-tour.md, most of which are explicitly linked to this issue. (One is linked to #1117, and two have no linked issue.)

Not linked to any issue:
- [ ] Point to coverage of ! and late
- [ ] move/add for-in coverage to language tour?

Already linked to this issue:
- [ ] Look for null, ?, !, late, optional, Map, List, Set.
- [ ] Make sure that points to a place that talks about const constructors,...
- [ ] Add coverage of void to the language tour.
- [ ] add test code
- [ ] Update if/when we drop support for `:`.
- [ ] make sure `?..` is covered in /null-safety
- [ ] Maybe change example or point to discussion of ! (in map section?).
- [ ] It isn't idiomatic to use a constructor for an empty Map. Change to a class that doesn't have literal support.

**Comment by atsansone** [comment]
@MaryaBelanger : FYI. Add this to your planning please.
