### ISSUE TITLE
Make updates null safety codelab

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3093]
#2983 created the null safety codelab. Here's how we should follow up, in rough order of most urgent/easy to less urgent/easy:

- [x] Add /codelabs/null-safety to the list of codelabs in /codelabs (#3112)
- [x] Listof -> ListOf: https://github.com/dart-lang/site-www/pull/2983#discussion_r598166849 (#3112)
- [x] Add link to this bug from the null safety codelab, and perhaps explicitly mention features that aren't covered (yet) (#3112)
- [x] Retire the [null safety tour](https://dart.dev/null-safety/tour), in favor of the codelab (#3112)
- [x] Redo the late variable example: https://github.com/dart-lang/site-www/pull/3167
- [ ] Add hints & tests to the examples
- [ ] Add coverage of other features, such as `required`, `?.`, and `?..`

**Comment by parlough** [comment]
If we want to keep the codelab, they are still relevant.
