### ISSUE TITLE
Update and improve the zones page

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4348]
Page URL: https://dart.dev/articles/archive/zones

Page source: https://github.com/dart-lang/site-www/tree/main/src/_articles/archive/zones.md

The [Dart Zones](https://dart.dev/articles/archive/zones) page is the only document covering zones but it is out of date, has issues, and is not following the website's current documentation and writing guidelines. We should update or completely replace it.

Some issues that the current page has for reference:

- [ ] Code does not follow Dart 2 standards, formatting, or suggested linter rules
- [ ] Some code/explanations are now incorrect
- [ ] Code is not tested
- [ ] Writing and structure does not match current site standards
- [ ] "A zone represents the asynchronous dynamic extent of a call" section is too technical and doesn't explain vocabulary (https://github.com/dart-lang/site-www/issues/2147)
- [ ] "Child zones don’t completely replace their parent zone" is not clear enough about what is replaced and what isn't (https://github.com/dart-lang/site-www/issues/2149)
- [ ] "A simple rule determines where errors are handled in a sequence" does not explain what the simple rule is (https://github.com/dart-lang/site-www/issues/2150)
- [ ] "the original zone must be the one that executes the microtask" has no explanation of why (https://github.com/dart-lang/site-www/issues/2151)
- [ ] "The run parameter also works for the initial, synchronous code that executes just after calling runZoned()." doesn't explain what the synchronous code is (https://github.com/dart-lang/site-www/issues/2153)
- [ ] `runZoned` will no longer have an `onError` parameter and must use `runZoneGuarded` (https://github.com/dart-lang/site-www/issues/4224)
- [ ] Error zones may be removed from zones (https://github.com/dart-lang/sdk/issues/49457)
