### ISSUE TITLE
Improve discussion around `const` and `const` constructors in language tour

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4350]
### Page URL

https://dart.dev/guides/language/language-tour

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/language/language-tour.md

### Describe the problem

The documentation around `const` was never fully fleshed out and there are some questions remaining. 

Some current issues:

- [ ] When `const` should be used, potential trade-offs, etc (https://github.com/dart-lang/site-www/issues/1061)
- [ ] Limitations of `const` constructors (https://github.com/dart-lang/site-www/issues/2010)
- [ ] Better clarity on what happens when in a constant context vs not (https://github.com/dart-lang/site-www/issues/1859)
- [ ] Better clarity on when `const` isn't necessary (https://github.com/dart-lang/site-www/issues/1364)

### Expected fix

We should go through the language tour and make sure `const` is well explained as well as how and when to use it.

**Comment by antfitch** [comment]
I think this was addressed as some point as I haven't seen any new asks since 2019 and we've got a section on it here that looks robust: https://dart.dev/language/variables#final-and-const

Tentatively closing.
