### ISSUE TITLE
☂ [Tracking] Isolates and Memory Management

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4571]
# WIP
(the issue itself is a WIP, I will add all the notes I want to incorporate later)

A reader commented on the [`Isolate.run()` blog](https://medium.com/dartlang/better-isolate-management-with-isolate-run-547ef3d6459b) wondering _exactly_ how data passes from parent to child isolate. 

@lrhn and @mkustermann provided some detailed notes answering the question, (which I'll add to this issue) and I think this information should be synthesized and added to our isolate docs ([this section](https://dart.dev/guides/language/concurrency#performance-and-isolate-groups) probably)

----

- [x] https://github.com/dart-lang/site-www/issues/4095
- [x] https://github.com/dart-lang/site-www/issues/4408
- [x] https://github.com/dart-lang/site-www/issues/4789
- [ ] https://github.com/dart-lang/site-www/issues/4419

**Comment by antfitch** [comment]
Tentatively closing due to the age of the issue.
