### ISSUE TITLE
The "Language" umbrella

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4588]
This issue is about disassembling the Language tour page (see #4565). To have a clean slate to unpack the language tour into, this also covers moving some of the existing content to more suitable locations.

### New structure proposal
Top level bullets are what's visible when you first expand "Language" in the left nav.

Second level bullets will either just be individual pages or combined with other topics on a single page. 
(Will decide per topic how to organize, but for the sake of time, second level bullets will all be on the parent page to begin with (for example, there's one page named "Types" and that has sections for all the built-in types, records, and typedefs)).

> Language tour _(previously "Language")_
> - Basics 
>   - [A basic Dart program](https://dart.dev/guides/language/language-tour#a-basic-dart-program)
>   - [Important concepts](https://dart.dev/guides/language/language-tour#important-concepts)
>   - [Keywords](https://dart.dev/guides/language/language-tour#keywords)
>   - [Variables](https://dart.dev/guides/language/language-tour#variables)
>   - [Operators](https://dart.dev/guides/language/language-tour#operators)
>   - [Metadata](https://dart.dev/guides/language/language-tour#metadata) _I moved this up from the bottom of the language tour to consolidate_
>   - [Comments](https://dart.dev/guides/language/language-tour#comments) _I moved this up from the bottom of the language tour to consolidate_
> - Types 
>   - [Built-in types](https://dart.dev/guides/language/language-tour#built-in-types)
>   - Collection types (will include [lists](https://dart.dev/guides/language/language-tour#lists), [maps](https://dart.dev/guides/language/language-tour#maps), and records (new))
>   - [Typedefs](https://dart.dev/guides/language/language-tour#typedefs) _Not originally under "Types", I added it here to consolidate_
>   - [Generics](https://dart.dev/guides/language/language-tour#generics) _Not originally under "Types", I added it here to consolidate_
> - [Control flow](https://dart.dev/guides/language/language-tour#control-flow-statements)
> - [Exceptions](https://dart.dev/guides/language/language-tour#exceptions)
> - Functions
>   - [Functions](https://dart.dev/guides/language/language-tour#functions)
>   - [Parameters](https://dart.dev/guides/language/language-tour#parameters)
>   - [The main() function](https://dart.dev/guides/language/language-tour#the-main-function)
>   - [Functions as first-class objects](https://dart.dev/guides/language/language-tour#functions-as-first-class-objects)
>   - [Anonymous functions](https://dart.dev/guides/language/language-tour#anonymous-functions)
>   - [Lexical scope](https://dart.dev/guides/language/language-tour#lexical-scope)
>   - [Lexical closures](https://dart.dev/guides/language/language-tour#lexical-closures)
>   - [Testing functions for equality](https://dart.dev/guides/language/language-tour#testing-functions-for-equality)
>   - [Return values](https://dart.dev/guides/language/language-tour#return-values)
>   - [Generators](https://dart.dev/guides/language/language-tour#generators) _Not originally under "Functions", I added it here to consolidate_
> - Classes and objects 
>   - [Using class members](https://dart.dev/guides/language/language-tour#using-class-members)
>   - [Using constructors](https://dart.dev/guides/language/language-tour#using-constructors)
>   - [Getting an object’s type](https://dart.dev/guides/language/language-tour#getting-an-objects-type)
>   - [Instance variables](https://dart.dev/guides/language/language-tour#instance-variables)
>   - [Constructors](https://dart.dev/guides/language/language-tour#constructors)
>   - [Methods](https://dart.dev/guides/language/language-tour#methods)
>   - [Abstract classes](https://dart.dev/guides/language/language-tour#abstract-classes)
>   - [Implicit interfaces](https://dart.dev/guides/language/language-tour#implicit-interfaces)
>   - [Extending a class](https://dart.dev/guides/language/language-tour#extending-a-class)
>   - [Extension methods](https://dart.dev/guides/language/language-tour#extension-methods) _consolidate other [Extension methods](https://dart.dev/guides/language/extension-methods) page here_
>   - [Enumerated types](https://dart.dev/guides/language/language-tour#enumerated-types)
>   - [Adding features to a class: mixins](https://dart.dev/guides/language/language-tour#adding-features-to-a-class-mixins)
>   - [Class variables and methods](https://dart.dev/guides/language/language-tour#class-variables-and-methods)
>   - [Callable classes](https://dart.dev/guides/language/language-tour#callable-classes) _Not originally under "Classes and objects", I added it here to consolidate_
>   - Class modifiers (new) (will include sealed classes (new))
>   - Inline classes (new)
> - Patterns (new) _(edit to move below classes and objects)_
> - [Type system](https://dart.dev/guides/language/type-system) (same content)
> - Null safety (same content)
> - Asynchronous programming _(could also be "Concurrency")_ _(called "Asynchrony support" in the language tour)_
>   - [Futures, async, await](https://dart.dev/guides/language/language-tour#asynchrony-support)
>   - [Streams](https://dart.dev/articles/libraries/creating-streams)
>   - [Isolates](https://dart.dev/guides/language/concurrency) _previously "Concurrency"_ _Not originally under "Asynchrony support", I added it here to consolidate_
>   - [Zones](https://dart.dev/articles/archive/zones) _currently archived_

---------

### Old structure

The current top level structure and pages that are moving

> [Language](https://dart.dev/null-safety/understanding-null-safety#sidenav-2)
> - ~[Tour](https://dart.dev/guides/language/language-tour)~ 
_unpacked under top level Language_
> - [Type system](https://dart.dev/guides/language/type-system)
> - ~[Effective Dart](https://dart.dev/null-safety/understanding-null-safety#sidenav-2-3)~
_moves either to it's own top level section or under Resources_
> - ~[Coming from ...](https://dart.dev/null-safety/understanding-null-safety#sidenav-2-4)~
_temporarily move to Resources, will go under new "Learn Dart" section_
> - ~[Extension methods](https://dart.dev/guides/language/extension-methods)~
_consolidate with extension methods content under Classes and objects_
> - ~[Concurrency](https://dart.dev/guides/language/concurrency)~
_moves under Asynchronous programming_
> - ~[Numbers](https://dart.dev/guides/language/numbers)~
_moves under Development, rename to "Dart number representation"_
> - [Null safety](https://dart.dev/null-safety/understanding-null-safety#sidenav-2-8)
> - ~[Evolution](https://dart.dev/guides/language/evolution)~
_moves under Resources, rename to Language evolution_
> - ~[Specification](https://dart.dev/guides/language/spec)~
_moves under Resources, rename to Language specification_

----- 

### Steps

- [x] First, I'll open a PR to move everything crossed out in "Old structure" above, out from under Language.
  - https://github.com/dart-lang/site-www/pull/4604
- [x] ~Then, I'll open a PR to rename the Language section to Language tour, and create the new sections under Language tour~ Keeping it just "Language", created sections in same PR as moving content
- [x] ~Then, I'll open PRs for each of the level 2 sections, and move content into them~ Didn't do that, just opened one big PR #4612 
- [x] Edit to add: scan the entire site for any internal links to the language tour, we can at least fix those even if we still have to add redirects for any external links pointing to it.
- [x] Edit to add: refactor the actual directory structure to match the side nav
  - Did this for at least the new content (src/language/page)
  - Cleaning up the rest is going to be a separate piece of work #4608 
- [ ] (future) I'll unpack the "Type system" content into separate pages (it's very dense, would be nice to have a stand alone description of type inference, conceptual static checking, etc.)
- [ ]  (future) The null safety content will not remain structured the way it currently is (see #4603 / #4584)

**Comment by MaryaBelanger** [comment]
cc @atsansone @mit-mit for review

**Comment by MaryaBelanger** [comment]
@munificent What do you think of [Patterns in that spot](https://github.com/dart-lang/site-www/issues/4588#:~:text=here%20to%20consolidate-,Patterns%20(new),-Control%20flow)? I looked at Swift's language guide and patterns are only mentioned on the control flow page and error handling page, both in the context of switch/case. 

Obviously, patterns will come up in our switch/case docs too, but as far as dedicated patterns conceptual content goes, they don't have anything in their guide (they _do_ have a completely separate "Language Reference" that covers patterns, expressions, statements, etc, but we don't have anything comparable).

So I just want to confirm that having patterns top level, following "types" and preceding "control flow" and "exceptions" makes sense conceptually. Thanks!

**Comment by MaryaBelanger** [comment]
Update/idea: I got some feedback on the value of the language tour as a linear reading experience, from some developers on the team who personally appreciated reading the language tour from start to finish when they were learning Dart.

I think the side nav itself will replicate the TOC of what the language tour contains, but clicking through the language tour from the side nav definitely isn't as intuitive as scrolling down a single page.  

This brought up a few possibilities:

- Previous/Next buttons at the bottom corners of each page to move readers along and maintain the feeling of a sequential connection
- Keeping the language tour as a map of the language topics, and moving all the extensive detail out to the separate pages described in the original issue comment. 
  - this kind of reflects the ["getting started" guide](https://github.com/dart-lang/site-www/issues/4565#:~:text=Create%20a%20%22Getting%20Started%22%20guide) idea that we were imagining for outlining the site's overall narrative
  - we were planning to maintain the original language tour page anyway to manually link from the old sections to the new pages, so having a little summary content left for each of the topics would make that look more natural.

**Comment by atsansone** [comment]
This is a great start, though we should consider parallelism in your titles, as well as TOC titles vs page titles. I think those can be different.

Your top-level could all be nouns, but the second level could be verb-noun or something similar.

See:
- https://www.grammarly.com/blog/parallelism/
- https://owl.purdue.edu/owl/general_writing/mechanics/parallel_structure.html
- https://www.niu.edu/writingtutorial/grammar/parallelism.shtml

**Comment by MaryaBelanger** [comment]
Update/idea # 2: Another possible solution to keeping a single page language tour is using our "include" function (not sure what it is exactly) to build a single page out of the content that we separate out to individual pages. 

1. We remove the content of each section of the language tour to its own pages that go in the side nav (original outline above), 
2. But, we keep the `/language/language-tour` page and all the headings on that page.
    - That keeps any links pointing to the page safe.
3. Then, we can wrap the content on the new pages in the "include" function, and add it to the language-tour page under it's original heading.
    - We can add a _"This content now lives on <page-link>"_ disclaimer to each section
5. We can hide the original `language-tour` page from the side nav and from search results
    - So, we don't have any duplicate content issues, 
    - But, we still get the benefit of maintaining a single language tour page if anyone wants that.

**Comment by munificent** [comment]
I definitely like the idea of having patterns at the top level. It is conceptually a sibling to expressions, statements, and types, in that each is its own part of the language grammar.

I would probably push it down after "Classes and Objects". Unlike some other languages, patterns aren't core to Dart, so they can be introduced later. (In languages like ML and Haskell *every* place you bind a name, even simple variable declarations and function parameters is a use of a pattern, so you really have to understand them to get anywhere with the language. In Dart, we sort of bolted patterns on to the side but single variable declarations and parameters are still their own thing, for better or worse.)

**Comment by mit-mit** [comment]
I'd like to hear a bit more about the need for a single page that explains "everything", as I remain a bit unconvinced about when such a page would be useful.

I totally understand the need for a single-page short introduction to the language -- for that something like https://dart.dev/codelabs/dart-cheatsheet seems super useful. But I'm not sure I understand when someone would expect a single page that has *all details* about *all language features*....

**Comment by parlough** [comment]
I agree. I think if people are looking for a flow, the previous/next buttons you mentioned should be sufficient alongside the (future improved) cheatsheets and other "Learn Dart" material. 

On top of that, the whole include process will add extra steps to adding and maintaining content as well as slow down the build. There are technical implications as well, like if we add more embedded DartPads or otherwise running code, that page will likely have loading issues. Also we would have to somehow rewrite the heading types (h1-h6) in the single-page version as otherwise they would not be nested properly.

Essentially, the single-page experience would not be a high quality or well supported experience after this transition, so I think it's better to just not support it, and redirect to the new location.

**Comment by mit-mit** [comment]
Couple of high-level thoughts:

1. I think the null safety content needs to go much higher in the list of topics in the new structure. It's a fundenmental part of the type system

1. I wonder if the Type system page we currently have in the Language section needs to somehow be written into the rest of the content. Concretely there seems to be sub-topics in there that would be brought out -- e.g. Type inference should probably be discussed fairly early when introducing types on fields?

1. I don't love the "Basics" category; it seems like a somewhat arbitrary collection of things, some of which aren't all that basic... I think either we make it the bare basics (e.g. something like [this](https://kotlinlang.org/docs/basic-syntax.html), or we just start with https://dart.dev/codelabs/dart-cheatsheet (potentially renamed to 'Dart  basics')

How about something like:

* Variables and expressions
  - Variables
  - Built-in types
  - Type inference
  - Type conversion
  - Comments
  - Operators
  - Strings and interpolation
  - Metadata
  - Keywords

* Functions
[ as yours ]

* Complex types
  - Collection types
  - Special types (Object, Iterable, Never, etc.)
  - Records
  - Dynamic types
  - Typedefs
  - Generics

* Classes
[ as yours ]

* Null safety
  - Non-null vs nullable
  - Corrrectness
  - Flow analysis
  - Working with nullable topes
  - ~~Core library changes~~ 

* Control flow
  - if and else
  - for loops
  - while and do-while loops
  - break and continue
  - switch
  - assert

* Error handling
  - Exceptions
  - Errors
  - Try/catch/finally

```

**Comment by mit-mit** [comment]
> Where would you place async/concurrency topics in this outline? At the end? 

Yeah, I think towards the end works.

**Comment by parlough** [comment]
Some thoughts on null safety docs:

Currently the null safety topics are very heavily focused on migration, switching from the new type system to the old one, or literally updating the SDK and migrating the code. As a result, it seems best to leave the current null-safety docs outside of the new Language flow, as it doesn't really fit with the rest and includes a lot of unnecessary or complicated topics for learners. The [Understanding null safety](https://dart.dev/null-safety/understanding-null-safety#non-nullable-and-nullable-types) article is amazing but goes into extreme detail and includes a lot of comparisons to the old way of doing so. This is great and we should incorporate these details eventually, but we also need a more introduction focused on new learners rather than old Dart users.

The solution in the long term is to introduce new, fleshed out type system documentation including that information as well as other updates alongside https://github.com/dart-lang/site-www/issues/4603. That is a larger undertaking though, so in the mean-time, we could introduce a **Nullable types** article with the basics needed to continue along with the language tour. It can link to **Understanding null safety** for more information.

Then the existing **/null-safety** docs, which are currently mostly focused on migration, could be placed under **Development** or its own top-level.

Tracking issue for future null safety updates and cleanup: https://github.com/dart-lang/site-www/issues/4603

**Comment by atsansone** [comment]
@mit-mit : I concur with @parlough here. We should keep the new Language section as a reference of the language. Null safety doesn't fit as written, which may make it a follow up case.

**Comment by MaryaBelanger** [comment]
I definitely agree with the null safety issue. I'm going to keep the linked PR as is for the sake of moving along, but follow up ASAP with work on extracting the useful parts of the null safety content into a new Nullable Types page. That will be a significant undertaking
