### ISSUE TITLE
Update language tour for Dart 2 changes

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#507]
* [x] Implicit new and const - lrn (dart-lang/sdk#30921) (partially fixed in #677)
* [x] Support assert in initializers - rnystrom (dart-lang/sdk#30968) (fixed in #677)
* [x] Fixed-sized integers limited to 64 bits - floitsch (dart-lang/sdk#28595, issue #591 ) (fixed in #677)
* [x] Generalized void - eernst (dart-lang/sdk#30176) (fixed [partially?] in #677)
* [ ] Eliminate fuzzy arrows - leafp (dart-lang/sdk#29630)
* [x] Start async functions synchronously - floitsch (fixed in #677)
* [x] @proxy & noSuchMethod (issue #442, pr #511)
* [x] First arg to assert can't be a function (issue #572)
* [x] Introduce generic syntax earlier (issue #588) (fixed in #677)
* [x] Asserts in initializers

**Comment by kwalrath** [comment]
I'm working on the strong mode changes, which are pretty invasive.

**Comment by sethladd** [comment]
This is so awesome to see!

**Comment by kwalrath** [comment]
I don't know how to update the language tour for fuzzy arrows, so I'll be contacting @leafpetersen. We expect to start using implicit new/const everywhere for beta 3.

**Comment by kwalrath** [comment]
We should cover asserts in initializers (and probably beef up the initializer coverage a bit).

**Comment by kwalrath** [comment]
I'm starting on removing `new` and `const`.

**Comment by chalin** [comment]
> I'm starting on removing `new` and `const`.

There is a PR pending for that: Remove all uses of "new" and "const" from "Effective Dart" #844. In particular, note this comment: https://github.com/dart-lang/site-www/pull/844#issuecomment-395498524. If we have the green light to go ahead with this, then great!

**Comment by kwalrath** [comment]
> > I'm starting on removing `new` and `const`.
> 
> There is a PR pending for that: _Remove all uses of "new" and "const" from "Effective Dart"_ #844. In particular, note this comment: https://github.com/dart-lang/site-www/pull/844#issuecomment-395498524. If we have the green light to go ahead with this, then great!

Because Flutter's style (at least within constructors) is not to use `new`, I've been asked to avoid `new` whenever possible. The bar for Effective Dart is higher, because it sets conventions used everywhere.

**Comment by kwalrath** [comment]
Implicit new and const are covered. I don't _think_ we need to cover fuzzy arrows, but I should probably still add an example of an assert in an initializer.

**Comment by kwalrath** [comment]
#677 added an example of using assert in an initializer.
