### ISSUE TITLE
☂️  [3.2] Evaluate changelog

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5338]
## This is an _evaluation_ issue

Evaluating the _possible_ need for doc updates due to [3.2 changelog](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#320) entries.

### Summary

Listing out the changes in one ticket and will link to others if necessary (not anticipating much).
Details on each can be found in the changelog

### Evaluation

- [x] Private final field promotion:
    - #4254 
- [x] Split point for refutable patterns
    - Fixing a bug/failure, failure wasn't documented, so now it just works how it "should".  No change.
- [x] Added `broadcast` parameter to `Stream.empty` constructor
    - No mention of broadcast streams or empty streams anywhere in the docs, so nowhere to add that you can change the default now.
- [x] Changed return types of `utf8.encode()` and `Utf8Codec.encode()`
    - https://github.com/dart-lang/site-www/pull/5115
- [x] Deprecated the `Service.getIsolateID` method.
    - Not mentioned in docs. 
- [x] Added `getIsolateId` method to `Service`.
    - Not sure how/where this would be used, but since there's no mention of the previous deprecated method, I assume there's no need to mention this one anywhere either
- [x] Added `getObjectId` method to `Service`.
    - Searched for any discussion about object IDs, didn't find anything. Not sure where this might be useful to use.
- [x] `dart:ffi`:
    - found incomplete sentence in diagnostic messages:
       https://github.com/dart-lang/sdk/issues/54036
    - #5336 
- [x] `HttpClientResponse.headers` and `HttpRequest.headers` return headers and fold points
    - Nothing about fold points or trailing whitespaces. 
- [x] `Isolate.packageConfigSync` and `Isolate.resolvePackageUriSync`
    - Nothing. 
- [x] JSInterop (skip)
- [x] DDC
- [x] dart2js
- [x] `dart create` command has a new cli template
    - #5249 
- [x] dart format 
    - Not sure if mentioning `--enable-experiment` for language experiments is useful or not.
- [x] Lints:
    - [`annotate_redeclares`](https://dart.dev/tools/linter-rules/annotate_redeclares)
    - [`use_build_context_synchronously`](https://dart.dev/tools/linter-rules/use_build_context_synchronously)
- [x] Pub:
    - [x]  `dart pub upgrade --tighten`
        - #5342 
    - [x]  `dart pub get/add/upgrade` now shows changes between direct, dev and transitive dependency
        - None of their docs mention that they "show" anything (assuming when it's run from the command line), so there's nothing to update and probably don't need to add it now...?
    - [x]  `dart pub upgrade` no longer shows unchanged dependencies
        - Thought this was already the case?
