### ISSUE TITLE
☂️ Help Dart developers navigate Dart's platform interoperability support

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#5475]
## Overview

This is an overarching project that will continue throughout the year and beyond, as we aim to help Dart developers learn about, understand, use, and build on Dart's evolving platform interoperability support. Over the past few years, Dart's interop story has completely changed, and we're long past the world of having to use the embedder API or native VM extensions. As Dart (and Flutter) target many platforms, this development has occurred in many different forms and many different places, but we're at a point where it's all coming together. Now it's our job to help Dart developers actually understand how it comes together and how to take advantage of that in their own projects.

## Structure

**To be filled in...**

## Subtasks

The following is an incomplete and in progress list, but groups some related tasks and issues:

### Introduce developers to interoperability and help them determine next steps

- [ ] https://github.com/dart-lang/site-www/issues/5364
- [ ] https://github.com/dart-lang/site-www/issues/5439
- [ ] https://github.com/dart-lang/site-www/issues/4563
- [ ] https://github.com/dart-lang/site-www/issues/5286

### Teach developers how to interop with native platforms

- [ ] https://github.com/dart-lang/site-www/issues/3084
- [ ] https://github.com/dart-lang/sdk/issues/54505
- [ ] Provide better guidance on interacting with Dart code from the native side
- [ ] Help Flutter developers understand when to use ffi vs pigeon

### Help developers publish packages and plugins that use native interop

- [ ] https://github.com/dart-lang/site-www/issues/5388
- [ ] Provide an end-to-end example of building and publishing a package

### Teach developers how to use and/or migrate to Dart's new JS static interop

- [ ] https://github.com/dart-lang/site-www/issues/5438
- [ ] https://github.com/dart-lang/site-www/issues/4177
- [ ] Help developers use JS interop with non-web targets

### Document the Wasm platform and any relevant interop functionality

- [ ] Explain Wasm support status and limitations
- [ ] Clarify support is for compiling to Wasm, not running
- [ ] Document how to interop with web/JS
- [ ] Add examples for interacting with Dart from Wasm source

### Provide some guidelines and best practices for developers

- [ ] Put more emphasis on generating any bindings
- [ ] https://github.com/dart-lang/site-www/issues/3193
- [ ] https://github.com/dart-lang/sdk/issues/33920
- [ ] Document some common issues to look out for

### Enable developers to adapt their app to different platforms

- [ ] https://github.com/dart-lang/site-www/issues/5334
- [ ] https://github.com/dart-lang/site-www/issues/4225
- [ ] https://github.com/dart-lang/site-www/issues/4175

### Help developers understand differences between platforms

- [ ] https://github.com/dart-lang/site-www/issues/5345
- [ ] https://github.com/dart-lang/site-www/issues/5107
- [ ] https://github.com/dart-lang/site-www/issues/3679

**Comment by andycall** [comment]
> Teach developers how to interop with native platforms

I’m writing a series of articles to teach Dart developers how to use FFI effectively, aimed at helping those without much native development experience.

[Memory Management in Dart FFI](https://medium.com/p/24577067ba43)
[How to Debug Your C/C++ Codes in Flutter](https://medium.com/@andycall/how-to-debug-your-c-c-codes-in-flutter-apps-22551e746c12)
