### ISSUE TITLE
Remove "/articles" directory

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#5766]
The content within it should be moved somewhere more appropriate or removed as well.

- [x] `/articles/libraries/creating-streams` (https://github.com/dart-lang/site-www/pull/5771)
- [ ] `/articles/archive/converters-and-codecs` (https://github.com/dart-lang/site-www/issues/5175, https://github.com/dart-lang/site-www/pull/5788)
- [x] `/articles/archive/numeric-computation` (https://github.com/dart-lang/site-www/pull/5776)
- [ ] `/articles/archive/zones` (https://github.com/dart-lang/site-www/issues/4348, https://github.com/dart-lang/site-www/pull/5788)
