### ISSUE TITLE
[Meta] Site changes for Dart 2

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#637]
We're using the [2-beta2 milestone](https://github.com/dart-lang/site-www/milestone/5) to track the most urgent Dart 2 issues, but here's a summary of the pages on the site and what might need to change. (Less urgent changes are under the [2-beta3 milestone](https://github.com/dart-lang/site-www/milestone/6).)

**Note:** The 2-dev version of the website is staged at https://dartlang-org-dev.firebaseapp.com. The current (1.x) version of the website will live on (and is hand-staged) at https://v1-dartlang-org.firebaseapp.com.

- [x] [Homepage](https://www.dartlang.org) - #653, #693 @anders-sandholm with support from @kwalrath (PR: #665, #750)
- [x] Language
  - [x] [Overview](https://www.dartlang.org/guides/language) - @kwalrath (minor)
  - [x] [Tour](https://www.dartlang.org/guides/language/language-tour) - #507 @kwalrath (2-beta2 changes done; more to come for beta3)
  - [x] [Effective Dart](https://www.dartlang.org/guides/language/effective-dart) and subpages - #632 @munificent (for now, @kwalrath has added a "Not Dart 2 compatible yet" banner: #688)
  - [x] [Sample Code](https://www.dartlang.org/samples) - #655 @kwalrath (dropped the cookbook in #687, should maybe change samples, but that could wait for beta3)
  - [x] "Strong Mode Dart" pages all need updates to change "strong mode" back to "sound Dart" (see [this diff](https://github.com/dart-lang/site-www/commit/6789bdf0725cddb7eb766b3637a7c3bc3ab1dc3c#diff-db463bf6e99ff3398977e0289f2026c7)), reflect the latest tool status, fix [known issues](https://github.com/dart-lang/site-www/issues?q=is%3Aissue+is%3Aopen+strong+mode+label%3ASoundDart) - @kwalrath (PR: #694)
    https://www.dartlang.org/guides/language/sound-dart
    https://www.dartlang.org/guides/language/sound-faq
    https://www.dartlang.org/guides/language/sound-problems
  - [x] https://www.dartlang.org/guides/language/analysis-options - #689 @kwalrath (get rid of "Specifying strong mode", 1.x, ...) (PR: #694)
  - [x] https://www.dartlang.org/guides/language/spec - OK as is?
- [x] Libraries
  - [x] [Overview](https://www.dartlang.org/guides/libraries) - OK as is.
  - [ ] [Commonly Used Dart Libraries](https://www.dartlang.org/guides/libraries/useful-libraries) - #656 (needs review, especially of 3rd party package list)
  - [x] [Create Library Packages](https://www.dartlang.org/guides/libraries/create-library-packages) - OK as is.
  - [x] [Tour](https://www.dartlang.org/guides/libraries/library-tour) - #506 (is tested, but maybe additional changes will be needed)
- [x] [Dart VM](https://www.dartlang.org/dart-vm) - Decision: Keep it as is. Update or banner, if appropriate.
  - [x] https://www.dartlang.org/dart-vm/dart-by-example - Delete this, but leave the repo (https://github.com/dart-lang/dart-samples; #655)
  - [x] https://www.dartlang.org/dart-vm/io-library-tour - OK as is.
  - [x] https://www.dartlang.org/dart-vm/tools - OK as is.
  - [x] https://www.dartlang.org/dart-vm/tools/dart-vm - #690 
- [ ] [Resources](https://www.dartlang.org/resources) - #929
  - [x] [Install](https://www.dartlang.org/install/archive) and subpages - #657 (can keep as is, for now, but soon we want separate SDK vs. web install flows, even if that means duplicated content) (PR: #727) @chalin 
  - [x] [Codelabs](https://www.dartlang.org/codelabs) - OK as is, but the actual codelabs (which are all on other sites) should be updated.
  - [x] [Tutorials](https://www.dartlang.org/tutorials) - #664 (review all tutorials; review index page just before milestone)
  - [x] [Articles](https://www.dartlang.org/articles) - #663 (no need to update now, but consider removing some; put a warning banner on the rest) (PR #699)
  - [x] [Dart Tips](https://www.dartlang.org/resources/dart-tips) - #670 (remove all)
  - [x] [Tools](https://www.dartlang.org/tools) - Review index page just before milestone.
    - [x] [Static Analyzer](https://www.dartlang.org/tools/analyzer) - OK as is.
    - [x] [SDK](https://www.dartlang.org/tools/sdk) - OK as is.
    - [x] [DartPad](https://www.dartlang.org/tools/dartpad) - #659 (will need new screenshots)
    - [x] [Tools FAQ](https://www.dartlang.org/tools/faq) - needs review (low priority?)
    - [x] [JetBrains Plugin](https://www.dartlang.org/tools/jetbrains-plugin) - #660 (update to remove Dartium; PR #699)
    - [x] [Pub](https://www.dartlang.org/tools/pub) - #649 (update/remove pages that refer to build/serve, barback, and transformers) (PRs: #703, #706)
  - [x] [Community and Support](https://www.dartlang.org/community) - OK as is.
- [x] Misc other pages that are OK as is:
  - [x] [Get Started](https://www.dartlang.org/guides/get-started), [Platforms](https://www.dartlang.org/guides/platforms), [Testing](https://www.dartlang.org/guides/testing), [What Not to Commit](https://www.dartlang.org/guides/libraries/private-files), [Code of Conduct](https://www.dartlang.org/code-of-conduct), [Who Uses Dart](https://www.dartlang.org/community/who-uses-dart), [Sitemap](https://www.dartlang.org/map), [Search](https://www.dartlang.org/search.html), [Terms](https://www.dartlang.org/terms).
  - [x] [Author pages](https://www.dartlang.org/resources/authors) for [Bob](https://www.dartlang.org/resources/authors/bob-nystrom), [Florian](https://www.dartlang.org/resources/authors/florian-loitsch), and [Gilad](https://www.dartlang.org/resources/authors/gilad-bracha), which I've confirmed are still visited.
- [ ] Misc other pages:
  - [x] [Dart 2 Updates](https://www.dartlang.org/dart-2) - Recast this as a migration guide. Related: #549, #662.
  - [x] [Performance](https://www.dartlang.org/performance) - #661 (remove it) (PR: #707)
  - [x] [Guides index](https://www.dartlang.org/guides) - Review just before milestone.
  - [x] [FAQ](https://www.dartlang.org/faq) - #366 @anders-sandholm (very out of date, but not prominently linked to)
  - [X] [Publications about Dart](https://www.dartlang.org/resources/books) - #807 updates the page to say that all pubs cover Dart 1.x. We'll need a little infrastructure change to add a Dart 2 section (#806).
  - [x] [Synonyms](https://www.dartlang.org/resources/synonyms) - #260. Plan is to **remove this**, but we'd be happy for someone else to take this over.
  - [ ] [Futures and Error Handling](https://www.dartlang.org/guides/libraries/futures-error-handling) - not tested, should probably be part of asynchrony doc consolidation (see #512).

Examples:
- [x] Adjust tests for full Dart 2 runtime semantics; enable --preview-dart-2 for example tests #908

Non-content changes:

- [x] Switch www.dartlang.org from Dart 1.x to Dart 2. #654 @chalin 
- [x] Update Dart icon, website color scheme, and design. #651 @filiph @chalin (PR: #830). Followups:
  - [x] Drop favicon.ico in favor of a single icon.png #834
  - [x] Update dartpad images once it is updated with the new Dart logo favicon #833
- [x] Footer: use primary brand blue background with monochrome logo #848
- ~Use web logo for web platform rather than Angular shield #849~

Changes on other sites:

- [x] Update Dart icon, website color scheme on Pub -  @isoos, https://github.com/dart-lang/pub-dartlang-dart/issues/1249
- [x] Update Dart icon in Jetbrains plugin - @devoncarew, https://github.com/dart-lang/sdk/issues/33017
- [x] Update Dart icon in VS Code plugin - @DanTup, https://github.com/Dart-Code/Dart-Code/issues/863
- [x] Update Dart icon, website color scheme on webdev - @kwalrath with @chalin 
- [x] Replace logo etc. on https://github.com/dart-lang/logos - https://github.com/dart-lang/logos/pull/4 @chalin
- [x] Update Dart icon on dartlang twitter account - ??
- [x] Update DartPad favicon https://github.com/dart-lang/dart-pad/issues/811 has been committed; not sure when the site will be updated.
  - [x] Update dartpad images once it is updated with the new Dart logo favicon #833
- [x] Update api.dartlang.org favicon (https://github.com/dart-lang/dartdoc/issues/1689) - https://github.com/dart-lang/dartdoc/pull/1690 @chalin
- [x] Update Dart icon on reddit (https://www.reddit.com/r/dartlang/) - @kwalrath sent email to moderators; https://www.reddit.com/user/knome made the change.
- [ ] Update Dart icon on SO (https://stackoverflow.com/tags/dart/info) - @kwalrath sent email to DevRel.
- [x] Update Dart icon on gitter (https://gitter.im/dart-lang/home) - @kwalrath
- [x] Update codelabs (linked from https://www.dartlang.org/codelabs) - @kwalrath

**Comment by kwalrath** [comment]
There's also the homepage and any sitewide nav/scope changes (e.g. making clear that this site covers dart 2, and for dart 1.x go to ...).

**Comment by mit-mit** [comment]
@chalin can I suggest we move the items related to updating the icon to a separate bug?

**Comment by kwalrath** [comment]
@JekCharlsonYu is in charge of what's in this [meta] issue. (It all shows up as @chalin because he opened the original issue.)

**Comment by JekCharlsonYu** [comment]
@mit-mit We were just trying to make sure that we have a place that shows up all related changes that we have with regard to the website - be it content or the actual website/logo changes. We are using this meta issue to track all the changes for dart2 properties.  

I think this is better to see a more comprehensive lists and at any rate, each item has their own related issues anyway.

**Comment by chalin** [comment]
(Closed by mistake)

**Comment by kwalrath** [comment]
I'm closing this issue, since the only remaining work to do is covered by #656, #929, and #512 (plus the SO icon, which I'll deal with separately).
