### ISSUE TITLE
Review all tutorials for Dart 2

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#664]
Consider updating them or adding an "out of date" banner, for now.

- [x] [Language tutorials](https://www.dartlang.org/tutorials/language)
  - [x] https://www.dartlang.org/tutorials/language/futures - #512 suggests combining async/generator docs.
  - [x] https://www.dartlang.org/tutorials/language/streams - #512 suggests combining async/generator docs.
- [x] [Library tutorials](https://www.dartlang.org/tutorials/libraries)
  - [x] https://www.dartlang.org/tutorials/libraries/shared-pkgs - (OK for now: #692) 
- [x] [VM tutorials](https://www.dartlang.org/tutorials/dart-vm) (bannered: #691)
  - [x] https://www.dartlang.org/tutorials/dart-vm/cmdline
  - [x] https://www.dartlang.org/tutorials/dart-vm/get-started
  - [x] https://www.dartlang.org/tutorials/dart-vm/httpserver

**Comment by chalin** [comment]
All pages mentioned in this issue have been updated; #512 can be addressed separately.
