### ISSUE TITLE
Test code excerpts for the shared-pkgs tutorial

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#692]
To do:

* [x] Consider changing `stagehand web-simple` to something else. #986
* [x] Acknowledge the existence of `flutter` ~and `webdev`~ tools as alternatives to stagehand. #986
* [x] Update the pubspec (once Dart 2 is out). #986, #1041
* [ ] Test the code excerpts.
* [x] Avoid showing the import of `dart:html`. #986

**Comment by kwalrath** [comment]
Related: #985.
