### ISSUE TITLE
Remove new & const (most) everywhere

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#870]
- [x] Update language tour to avoid using new/const except where necessary. #507 
- [x] Add optional new/const to /dart-2. #945 
- [x] Update all **tested** code samples to NOT use new/const unless absolutely necessary. #966
- [x] Remove all uses of "new" and "const" from "Effective Dart". #844

**Comment by kwalrath** [comment]
We've updated all tested code samples, which means all of the most used/updated pages. @chalin, do you know whether everything else that might contain new and const is marked as obsolete?

**Comment by chalin** [comment]
> do you know whether everything else that might contain new and const is marked as obsolete?

No, I don't know.

**Comment by chalin** [comment]
I'm checking now to ensure that pages that need to be are marked as (potentially) out-of-date (using `obsolete: true`).

**Comment by chalin** [comment]
A few extra pages needed to be marked as obsolete, see #973.

**Comment by chalin** [comment]
The analyzer is checking for `unnecessary_const` and `unnecessary_new` in all examples (#1026). No issues are reported, so I'd say that we're done!
